# Development docker-compose
version: '3'
services:
  database:
    container_name: diploma-database
    image: postgres:13
    network_mode: host
    environment:
      POSTGRES_DB: diploma-dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /var/pgdata
    volumes:
      - ./data:/var/pgdata
